### PR TITLE
added an option for importing only the tiles used in the map,…

### PR DESCRIPTION
**Pull request by vichug**
… and not the whole tilesets. Can reduce significantly the size of the Godot scene file and the overall working time with said tilesets. This option shouldn't be used always, because it has the obvious drawback that it will import the Tiled tilesets only partially.

### CODE REVIEW

**Comment by MrGreenTea** [comment]
Can't automatically merge it. Could you take a look and implement your changes after I merged the other two PRs?

**Comment by vichug** [comment]
Is that because you are merging other requests in between ? If that's so, of course i'll be able to redo it wiht the latest version on the git (should not be a lot of work)

**Comment by MrGreenTea** [comment]
yeah I tried to merge all pull requests yesterday. Would be great if you could do that!

**Comment by vichug** [comment]
i can't find a way to create a new pull request from my fork... it's not impossible that you have to close this present pull request first, before i can open another with the up-to-date version of my fork. 

However the way i did it might be improper : since i saw that ; in fine ; all that changed since i made this pull request was one line _(i saw that by diff'ing current 197ccc7 master commit and b8d5c43 from which i had forked)_ ; i added that line in my fork instead of {*destroying my fork, *forking again from your main current master branch *and then redoing all my changes} because it would be some more work.

I have hard time understanding branches and forks and merges... maybe if you close the pull request it won't actually solve anything. Maybe there is a clever way to do it effectively with branches etc but i really didn't find it. Maybe there actually isn't a simple way to do this, and i might be forced to do what i say earlier manually in the end...

**Comment by MrGreenTea** [comment]
I don't have much experience with git and don't know what you could do.

**Pull request closed without merging**
